### ISSUE TITLE
前方拥堵，请稍后再试

### ISSUE THREAD

**Issue by zelbloo** [JiajunJiang/RobFood#2]
depth(15) 的弹窗没有在case里，我手动添加也不能自动点击
![Screenshot_20220406-063255](https://user-images.githubusercontent.com/7335235/161862096-a73f5f0d-182d-46e0-9510-ae394e07b947.png)

**Comment by JiajunJiang** [comment]
depth(15) 是抓取出来的话 理论上应该是可以的 检查一下case的判断顺序是否有误

**Comment by JrDw0** [comment]
遇到了同样的情况，加了case，打了log看到脚本最终有输出一次“前方拥堵”，然后就没继续了。。也没抓到这个弹窗没法调试
```
// edit by JrD
const appName = "美团买菜";
launchApp(appName);
sleep(500);

auto.waitFor()
// 点击结算
const clickSettle = () => {
	className("android.view.View").depth(22).findOne().parent().click()
}
// 点击我知道了
const clickKnow = () => {
	className("android.view.View").depth(16).findOne().parent().click()
}
//点击放弃机会
const clickGiveup= () => {
	className("android.widget.TextView").text("放弃机会").findOne().parent().parent().click()
}
// 点击立刻支付
const clickPay = () => {
	className("android.widget.TextView").text("立即支付").findOne().parent().click()
}
//拥堵繁忙
const clickBusy = () => {
	className("android.widget.TextView").text("返回购物车").findOne().parent().click()
}
//约满
const clickFull = () => {
	className("android.widget.TextView").text("我知道了").findOne().parent().click()
}

const hasText = (text) => {
	return textStartsWith(text).exists() // 是否存在指定文本
}

const start = () => {
	console.show()
	if (hasText('立即支付')) 
    {
		console.log('立即支付')
		clickPay()
		sleep(500)
		start()
		console.log('抢到了')

	} 
    else if (hasText('放弃机会')) 
    {
		console.log('放弃机会')
		clickGiveup()
		sleep(500)
		start()
	} 
    else if (hasText('前方拥堵')) 
    {
		console.log('前方拥堵')
		clickBusy()
		sleep(500)
		start()
	} 
    else if (hasText('当前不在可下单时段') || hasText('很抱歉')) 
    {
		console.log('当前不在可下单时段')
		clickKnow()
		sleep(500)
		start()

	} 
    else if (hasText('配送运力已约满') ) 
    {
		console.log('已约满')
		clickFull()
		sleep(500)
		start()
	} 
	else if (hasText("结算"))
    {
		console.log("结算")
		clickSettle()
		sleep(500)
		start()
	} 
    else 
    {
        sleep(500)
		start()
	}
}

start()
```

**Comment by zelbloo** [comment]
>

**Comment by zelbloo** [comment]
> @JrDw0 
你把那个返回购物车用这个事件呢
className("android.view.View").depth(15).findOne().parent().click()

我抓到的是15

**Comment by JrDw0** [comment]
但是你不是说15也没办法点击？

**Comment by zelbloo** [comment]
> @JrDw0 
你可以试试，我不清楚判断顺序是不是正确，明天我再验证下

**Comment by zelbloo** [comment]
@JiajunJiang @JrDw0 
下面是我验证过可以用的了
auto.waitFor()
// 点击结算
const clickSettle = () => {
	className("android.view.View").depth(22).findOne().parent().click()
}
// 点击我知道了
const clickKnow = () => {
	className("android.view.View").depth(16).findOne().parent().click()
}
//点击放弃机会
const clickGiveup= () => {
	className("android.widget.TextView").text("放弃机会").findOne().parent().parent().click()
}
// 点击立刻支付
const clickPay = () => {
	className("android.widget.TextView").text("立即支付").findOne().parent().click()
}
//拥堵繁忙
const clickBusy = () => {
	className("android.view.View").depth(15).findOne().parent().click()
}
//约满
const clickFull = () => {
	className("android.widget.TextView").text("我知道了").findOne().parent().click()
}

const hasText = (text) => {
	return textStartsWith(text).exists() // 是否存在指定文本
}

const start = () => {
	console.show()
	if (hasText('立即支付')) 
    {
		console.log('立即支付')
		clickPay()
		sleep(500)
		start()
		console.log('抢到了')

	} 
    else if (hasText('放弃机会')) 
    {
		console.log('放弃机会')
		clickGiveup()
		sleep(500)
		start()
	} 
    else if (hasText('结算人数')) 
    {
		console.log('前方拥堵')
		clickBusy()
		sleep(500)
		start()
	} 
    else if (hasText('当前不在可下单时段') || hasText('很抱歉')) 
    {
		console.log('当前不在可下单时段')
		clickKnow()
		sleep(500)
		start()

	} 
    else if (hasText('配送运力已约满') ) 
    {
		console.log('已约满')
		clickFull()
		sleep(500)
		start()
	} 
	else if (hasText("结算"))
    {
		console.log("结算")
		clickSettle()
		sleep(500)
		start()
	} 
    else 
    {
        sleep(500)
		start()
	}
}

start()
