### ISSUE TITLE
跳转到显示到其他应用上层

### ISSUE THREAD

**Issue by timwhitez** [JiajunJiang/RobFood#3]
华为p30pro
提交几次后就会跳转到显示到其他应用上层的设置

但按钮为灰色无法进行设置。

**Comment by JiajunJiang** [comment]
这个应该EMUI的一些特殊权限吧，我身边也没有合适的设备可以测试。可以检查一下无障碍的权限有没有开通，或者把权限指定给买菜app

**Comment by timwhitez** [comment]
好像是悬浮窗的设置没办法给这个插件打开，但之前叮咚的那个插件是没这个问题的
https://github.com/Skykai521/DingDongHelper

大佬早点睡

**Comment by alanleung2017** [comment]
> 华为p30pro 提交几次后就会跳转到显示到其他应用上层的设置
> 
> 但按钮为灰色无法进行设置。

是鸿蒙2.0吗兄弟

**Comment by timwhitez** [comment]
> 

是的

**Comment by timwhitez** [comment]
> > 华为p30pro 提交几次后就会跳转到显示到其他应用上层的设置
> > 但按钮为灰色无法进行设置。
> 
> 是鸿蒙2.0吗兄弟

是的

**Comment by JiajunJiang** [comment]
1.先打开“设置”，点击“应用”，再点击“应用管理”。
2.接着，点击要显示上层的“应用”，并点击“显示在其他应用的上层”。
3.最后，点击打开“在显示在其他应用的上层”按钮即可。

刚刚有一个华为P40遇到了一样的问题，并附上了解决方案。

**Comment by alanleung2017** [comment]
> > > 华为p30pro 提交几次后就会跳转到显示到其他应用上层的设置
> > > 但按钮为灰色无法进行设置。
> > 
> > 
> > 是鸿蒙2.0吗兄弟
> 
> 是的

我的也是这样

**Comment by alanleung2017** [comment]
> 管理

你这个是鸿蒙2.0吗

**Comment by alanleung2017** [comment]
> 1.先打开“设置”，点击“应用”，再点击“应用管理”。 2.接着，点击要显示上层的“应用”，并点击“显示在其他应用的上层”。 3.最后，点击打开“在显示在其他应用的上层”按钮即可。
> 
> 刚刚有一个华为P40遇到了一样的问题，并附上了解决方案。

你这个是鸿蒙2.0吗
