### ISSUE TITLE
APK下载不了

### ISSUE THREAD

**Issue by Hao-000** [JiajunJiang/RobFood#7]
APK下载不了

**Comment by JiajunJiang** [comment]
试了一下应该是可以的 不过Github服务器不在国内 可能比较慢吧
有可以尝试手动下载 在Release里面
[美团买菜助手_v1.0.1.apk](https://github.com/JiajunJiang/RobFood/blob/main/Release/%E7%BE%8E%E5%9B%A2%E4%B9%B0%E8%8F%9C%E5%8A%A9%E6%89%8B_v1.0.1.apk)
